version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4567-4578:4567-4578
      - 8080:8080
    environment:
      - SERVICES=dynamodb,s3,lambda,apigateway
      - DEFAULT_REGION=ap-northeast-1
      - HOSTNAME=localhost
      - DYNAMODB_ERROR_PROBABILITY=0.0
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
